# Generated by Django 4.2.19 on 2025-02-10 17:34

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('mailinglist', '0003_alter_messagepart_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='text',
            field=tinymce.models.HTMLField(default='-'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='MessagePart',
        ),
    ]
