# Generated by Django 4.2.19 on 2025-02-12 21:15

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('mailinglist', '0004_message_text_delete_messagepart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='text',
        ),
        migrations.CreateModel(
            name='MessagePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=128)),
                ('order', models.PositiveSmallIntegerField()),
                ('text', tinymce.models.HTMLField()),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_parts', to='mailinglist.message')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddConstraint(
            model_name='messagepart',
            constraint=models.UniqueConstraint(fields=('message', 'order'), name='unique_order_per_message'),
        ),
    ]
