# Generated by Django 4.2.19 on 2025-02-14 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailinglist', '0005_remove_message_text_messagepart_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messagepart',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='messagepart',
            name='unique_order_per_message',
        ),
        migrations.RemoveField(
            model_name='messagepart',
            name='heading',
        ),
        migrations.RemoveField(
            model_name='messagepart',
            name='order',
        ),
    ]
