# Generated by Django 4.2.19 on 2025-02-14 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailinglist', '0006_alter_messagepart_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailinglist',
            name='language',
            field=models.CharField(default='es', help_text='ISO 639 language codes, set 1: https://en.wikipedia.org/wiki/List_of_ISO_639_language_codes', max_length=2),
        ),
    ]
