# Generated by Django 4.2.19 on 2025-02-19 16:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mailinglist', '0007_mailinglist_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailinglist',
            name='description',
        ),
        migrations.AlterField(
            model_name='submission',
            name='published',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
