# Generated by Django 4.2.19 on 2025-02-22 00:12

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('mailinglist', '0008_remove_mailinglist_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagepart',
            name='text',
            field=tinymce.models.HTMLField(help_text='%%NAME%%: subscriber name'),
        ),
    ]
