# Generated by Django 4.2.19 on 2025-02-22 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailinglist', '0009_alter_messagepart_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailinglist',
            name='language',
            field=models.CharField(help_text='ISO 639 language codes, set 1: https://en.wikipedia.org/wiki/List_of_ISO_639_language_codes', max_length=2),
        ),
    ]
