# Generated by Django 4.2.19 on 2025-02-07 11:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("test_project", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AdHocUserModel",
        ),
    ]
